WITH RECURSIVE TEMP AS(
    SELECT 0 AS H
    UNION ALL
    SELECT H+1 FROM TEMP
    WHERE H < 23
)

SELECT TEMP.H, COUNT(HOUR(o.DATETIME)) COUNT
FROM TEMP LEFT JOIN ANIMAL_OUTS as o
ON HOUR(o.DATETIME) = TEMP.H
GROUP BY TEMP.H
ORDER BY TEMP.H;