-- 1
SELECT CART_ID
FROM (
    SELECT CART_ID, GROUP_CONCAT(NAME) NAME
    FROM CART_PRODUCTS
    GROUP BY CART_ID
    )TMP
WHERE TMP.NAME LIKE '%Yogurt%' AND TMP.NAME LIKE '%Milk%';

-- 2
SELECT a.CART_ID
FROM CART_PRODUCTS a, CART_PRODUCTS b
WHERE a.CART_ID = b.CART_ID AND a.NAME LIKE "%Yogurt%" AND b.NAME LIKE "%Milk%";

-- 3
SELECT CART_ID FROM CART_PRODUCTS
WHERE name IN ('Milk', 'Yogurt')
GROUP BY CART_ID
HAVING COUNT(DISTINCT name) > 1;