SELECT o.ANIMAL_ID, o.ANIMAL_TYPE, o.NAME
FROM ANIMAL_OUTS o INNER JOIN ANIMAL_INS i
ON o.ANIMAL_ID = i.ANIMAL_ID
WHERE o.SEX_UPON_OUTCOME NOT LIKE '%Intact%' and i.SEX_UPON_INTAKE LIKE '%Intact%'
ORDER BY ANIMAL_ID;